// <auto-generated />
using System;
using CDR_Analytics.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDR_Analytics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250404195345_UpdateCDREntity")]
    partial class UpdateCDREntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CDR_Analytics.Entities.CDR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CallDate")
                        .HasColumnType("date");

                    b.Property<string>("CallerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CallDate")
                        .HasDatabaseName("Idx_CallDate");

                    b.HasIndex("CallerID")
                        .HasDatabaseName("Idx_CallerID");

                    b.HasIndex("Recipient")
                        .HasDatabaseName("Idx_Recipient");

                    b.ToTable("CDRs");
                });
#pragma warning restore 612, 618
        }
    }
}
