// <auto-generated />
using System;
using CDR_Analytics.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDR_Analytics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CDR_Analytics.Entities.CDR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("CallDate")
                        .HasColumnType("date");

                    b.Property<string>("CallerID")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Recipient")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CallDate")
                        .HasDatabaseName("Idx_CallDate");

                    b.HasIndex("CallerID")
                        .HasDatabaseName("Idx_CallerID");

                    b.HasIndex("Recipient")
                        .HasDatabaseName("Idx_Recipient");

                    b.ToTable("CDRs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
